### ISSUE TITLE
midterm clarifications

### ISSUE THREAD

**Issue by bbolker** [bbolker/stat4c03#1]
this thread is for questions/clarifications about the midterm (I'll post clarifications that seem of general interest; feel free to ask new questions here if you think you can ask them without too many spoilers).

**Comment by bbolker** [comment]
**question 1.1**: *what should I do about the fact that my aggregated data frame is missing some rows, i.e. combinations of factors for which there aren't any values in the data set?*

**A**: it's safe to ignore this, those combinations with zero observations won't affect any models you fit any case.

---
If you want to try to include these cases (maybe important to you in some future data-transformation task), you can add `drop=FALSE` if using `aggregate`, or use the `tidyr::complete()` function if using tidyverse (see [this StackOverflow question](https://stackoverflow.com/questions/25956178/proper-idiom-for-adding-zero-count-rows-in-tidyr-dplyr) (I know, you're not allowed to look at that right now, but bookmark it so you can read it after you submit your test)).

**Comment by bbolker** [comment]
**question 2**: *did you really mean to use the categories "< $50,000" and "≥ $50,000"? That's not what is in the data set*

**A**: that's a mistake. Use the categories that are in the data set.

**Comment by bbolker** [comment]
**questions 1.5, 1.6**: *what do you mean by `Age1:Class3` etc.?*

**A**: when using sum-to-zero contrasts, R labels the parameter corresponding to the difference of the *first* level of factor `fac`  from the (unweighted) average as `fac1`, the difference from the second level from the average as `fac2`, etc.. (It drops the difference of the *last* level from the average; otherwise the model would be overparameterized.) My question refers to these labels, so e.g. `Age1` refers to Adults (unless you explicitly switched the order of the factor levels from the alphabetical default, which is fine if you clearly explain what you did).

(This differs, confusingly, from the treatment-contrasts behaviour, which would have the baseline level as the intercept, and the difference of the *second* level from the baseline as the first coefficient, i.e. for the Titanic data set the first coefficient for `Age` would be labeled `AgeChild`.)

**Comment by bbolker** [comment]
**question 1.4**: *should I really ignore the custom contrasts I just defined in Q1.3 and use sum-to-zero contrasts for this question (and the remainder of part 1)?*

**A:** yes, that's what it says.

**Comment by dada1111** [comment]
for Q2.2 you said 3 predictor categorical variables, but there are more -- which ones should we use?
